apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: nginx
    name: nginx
    namespace: giropops
  spec:
    clusterIP: 10.104.167.226
    clusterIPs:
    - 10.104.167.226
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31397
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      run: nginx
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
